name: Terraform Deployment

on: [push, pull_request]

jobs:
  deploy:
    name: 'Terraform Deployment'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: terraform/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: "1.7.5"

      - name: Initialize Terraform
        run: terraform init

      - name: Check Terraform version
        run: terraform version

      - name: List files in working directory
        run: ls -al

      - name: Format Terraform files
        run: terraform fmt -check -recursive || echo "Terraform files need formatting"

      - name: Validate scripts
        run: terraform validate

      - name: Generate execution plan
        run: terraform plan -input=false

      - name: Scan for sensitive information
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          config: https://raw.githubusercontent.com/zricethezav/gitleaks/master/config/gitleaks.toml

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -compact-warnings -auto-approve -input=false